services:
  # 1. Database Service (Using official Mongo & auto-creating admin user)
  mongo-db:
    image: preranabl/demo-db:0.3.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongo_data:/data/db

  # 2. Message Broker
  message_broker:
    image: rabbitmq:3-management
    container_name: message_broker
    ports:
      - "5672:5672"   
      - "15672:15672" 

  # 3. Auth Service
  auth-service:
    image: preranabl/rest-auth:0.2.0
    container_name: rest-auth
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo-db:27017/auth_db?authSource=admin
    depends_on:
      - mongo-db

  # 4. Payment Service
  payment-service:
    image: preranabl/rest-payment:0.7.0
    container_name: rest-payment
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo-db:27017/payment_db?authSource=admin
      - RABBIT_URI=amqp://message_broker
    depends_on:
      - mongo-db
      - message_broker

  # 5. Notification Service
  notification-service:
    image: preranabl/rest-noti:0.2.0
    container_name: notification-service
    environment:
      - RABBIT_URI=amqp://message_broker
    depends_on:
      - message_broker

  # 6. Frontend Service
  frontend-service:
    image: preranabl/rest-fe:0.1.0
    container_name: rest-fe
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - payment-service

volumes:
  mongo_data:
