version: "3.9"

services:
  frontend:
    image: preranabl/multi-fe:1.0.0
    container_name: frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - payment

  auth:
    image: preranabl/multi-auth:1.0.0
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://host.docker.internal:27017/monolith-auth

  payment:
    image: preranabl/multi-payment:1.0.0
    container_name: payment-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://host.docker.internal:27017/monolith-payment
